components:
  - name: DocumentStore
    params:
      host: localhost
    type: ElasticsearchDocumentStore
  - name: Retriever
    params:
      document_store: DocumentStore
      embedding_model: sentence-transformers/multi-qa-mpnet-base-dot-v1
      model_format: sentence_transformers
      top_k: 25
    type: EmbeddingRetriever
  - name: Reader
    params:
      model_name_or_path: deepset/roberta-base-squad2
      use_gpu: true
      top_k: 5
    type: FARMReader
pipelines:
  - name: query
    nodes:
      - inputs:
          - Query
        name: Retriever
      - inputs:
          - Retriever
        name: Reader
version: 1.16.1rc1
